pipeline {
    agent any

    tools {
        maven 'maven 3.9.9' // Add a space after 'maven' for clarity
    }

    stages {
        stage("build") {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }

        stage("test") {
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker') {
                    sh 'mvn test'
                }
            }
        }

        stage("package") {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}

